var texts = {
	pt: {
		title:"Lucas Ferreira | Programador",
		name:"Lucas Ferreira",
		about:"Sobre",
		projects:"Projetos",
		resume:"Experiências",
		contact:"Contato",
		lang_swap_text:"English",
		color_mode_text:"Tema de cores",

		welcome:"Bem-vindo ao <span class=\"mobile-block\">site do meu portifólio!</span>",
		hello:"Olá, eu sou",
		animated_item_1:"Lucas Ferreira",
		animated_item_2:"Programador",
		animated_item_3:"Entusiasta",
		about_text:"Programador por natureza, que não passa um único dia sem estudar e não foge de situações difíceis.\
		 Assim como os softwares, nunca será perfeito, mas está em constante evolução.",
		attr_href_linkedin:"https://www.linkedin.com/in/lucas-costa-ferreira/",
		resume_link:"LinkedIn",

		projects_title:"Meus projetos",

		experiences_title:"Experiências profissionais",
		president:"Presidente",
		caee_president_desc:"",
		ac_director:"Diretor acadêmico",
		caee_ac_director_desc:"",
		ac_codirector:"Co-Diretor acadêmico",
		caee_ac_codirector_desc:"",
		system_assessor:"Assessor de Sistemas",
		ejeet_system_assessor_desc:"",
		it_assessor:"Assessor de Tecnologia da Informação",
		ejeet_it_assessor_desc:"",

		educations_title:"Experiências Acadêmicas",
		uftm_elect_eng:"Bacharel em Engenharia Elétrica",
		uftm_elect_eng_desc:"",
		attr_href_uftm:"http://uftm.edu.br",
		iftm_msi:"Técnico em Manutenção e Suporte em Informática",
		iftm_msi_desc:"",
		attr_href_iftm:"http://iftm.edu.br",

		contact_me:"Entre em contato",
		phone:"(34) 3314-0741",
		contact_form_title:"Vamos trabalhar juntos?",
		rights:"Todos os direitos reservados.",
		design_adapted:"Design adaptado de",
	},

	en: {
		title:"Lucas Ferreira | Programmer",
		name:"Lucas Ferreira",
		about:"About",
		projects:"Projects",
		resume:"Resume",
		contact:"Contact",
		lang_swap_text:"Português",
		color_mode_text:"Color mode",

		welcome:"Welcome to <span class=\"mobile-block\">my portfolio website!</span>",
		hello:"Hey, I'm",
		animated_item_1:"Lucas Ferreira",
		animated_item_2:"Programmer",
		animated_item_3:"Enthusiast",
		about_text:"Programmer by nature, who does not spend a single day without studying and does not run from difficult situations.\
		 Like softwares, it will never be perfect, but it is constantly evolving.",
		attr_href_linkedin:"https://www.linkedin.com/in/lucas-costa-ferreira/en",
		resume_link:"LinkedIn",

		projects_title:"My projets",

		experiences_title:"Experiences",
		president:"President",
		caee_president_desc:"",
		ac_director:"Academic Director",
		caee_ac_director_desc:"",
		ac_codirector:"Co Academic Director",
		caee_ac_codirector_desc:"",
		system_assessor:"Information System Assessor",
		ejeet_system_assessor_desc:"",
		it_assessor:"IT Assessor",
		ejeet_it_assessor_desc:"",

		educations_title:"Educations",
		uftm_elect_eng:"Bachelor of Electrical Engineering",
		uftm_elect_eng_desc:"",
		attr_href_uftm:"http://uftm.edu.br/en",
		iftm_msi:"IT Maintenance and Support Technician",
		iftm_msi_desc:"",
		attr_href_iftm:"http://iftm.edu.br/en",

		contact_me:"Contact me",
		phone:"+55 34 3314-0741",
		contact_form_title:"Let's work together?",
		rights:"All rights reserved.",
		design_adapted:"Design adapted from",
	}
};
